// scripts/after-nop.mjs
import fs from "node:fs";
import path from "node:path";

function copyDir(src, dest) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

const outRoot   = path.join(".vercel", "output", "static");
const workerDir = path.join(outRoot, "_worker.js");
const genIndex  = path.join(workerDir, "index.js");
const nextIndex = path.join(workerDir, "index.next.js");
const routes    = path.join(outRoot, "_routes.json");

// 1) Move the generated Next worker aside -> index.next.js
fs.mkdirSync(workerDir, { recursive: true });
if (!fs.existsSync(genIndex)) throw new Error(`Expected ${genIndex} not found`);
try { fs.unlinkSync(nextIndex); } catch {}
fs.renameSync(genIndex, nextIndex);

// 2) Copy your repo’s functions into the worker bundle
const repoFunctions = path.join("functions");              // <— your existing folder at repo root
const workerFunctions = path.join(workerDir, "functions"); // will live under _worker.js/
copyDir(repoFunctions, workerFunctions);

// 3) Create our wrapper that mounts API + /data and falls back to Next
const wrapperSrc = `
// Auto-generated by scripts/after-nop.mjs

const apiRoutes = {
  "/api/login":          () => import("./functions/api/login.js"),
  "/api/update":         () => import("./functions/api/update.js"),
  "/api/update-stream":  () => import("./functions/api/update-stream.js"),
  "/api/cancel-run":     () => import("./functions/api/cancel-run.js"),
  "/api/schedule":       () => import("./functions/api/schedule.js"),
  "/api/r2-diagnostics": () => import("./functions/api/r2-diagnostics.js"),
};

const dataRoute = /^\\/data\\/.+/;

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // 1) API (mounted handlers)
    if (url.pathname.startsWith("/api/")) {
      const loader = apiRoutes[url.pathname];
      if (!loader) return new Response("Not Found", { status: 404 });
      const mod = await loader();
      if (typeof mod.default === "function") return mod.default(request, { env, ctx });
      if (typeof mod.onRequest === "function") return mod.onRequest({ request, env, ctx });
      return new Response("Bad handler", { status: 500 });
    }

    // 2) /data/* from R2
    if (dataRoute.test(url.pathname)) {
      if (!env?.LEADERBOARDS) return new Response("R2 not bound", { status: 500 });
      const key = decodeURIComponent(url.pathname.replace(/^\\/data\\/?/, ""));
      if (!key) return new Response("Not found", { status: 404 });
      const obj = await env.LEADERBOARDS.get(key);
      if (!obj) return new Response("Not found", { status: 404 });
      const isJSON = key.endsWith(".json");
      return new Response(obj.body, {
        headers: {
          "Content-Type": isJSON ? "application/json" : "application/octet-stream",
          "Cache-Control": isJSON ? "public, max-age=3600, stale-while-revalidate=59"
                                  : "public, max-age=604800, immutable",
          "Access-Control-Allow-Origin": "*"
        }
      });
    }

    // 3) Everything else -> Next’s worker
    const nextWorker = await import("./index.next.js");
    return nextWorker.default.fetch(request, env, ctx);
  }
};
`;
fs.writeFileSync(genIndex, wrapperSrc, "utf8");

// 4) Remove _routes.json so our worker sees all requests
try { fs.unlinkSync(routes); } catch {}

console.log("✔ Wrapped Next worker, copied functions/, and removed _routes.json");
