// scripts/after-nop.mjs
import fs from "node:fs";
import path from "node:path";

const outRoot = path.join(".vercel", "output", "static");
const workerDir = path.join(outRoot, "_worker.js");
const generatedIndex = path.join(workerDir, "index.js");
const backupIndex = path.join(workerDir, "index.next.js");
const routesJson = path.join(outRoot, "_routes.json");

// Ensure paths exist
fs.mkdirSync(workerDir, { recursive: true });

// 1) Move the generated Next worker aside -> index.next.js
if (fs.existsSync(generatedIndex)) {
  // overwrite if re-running
  try { fs.unlinkSync(backupIndex); } catch {}
  fs.renameSync(generatedIndex, backupIndex);
} else {
  throw new Error(`Expected generated worker at ${generatedIndex} not found`);
}

// 2) Write our wrapper worker at index.js
// NOTE: adjust the relative import paths below if your functions folder is elsewhere.
const wrapper = `
// Auto-generated by scripts/after-nop.mjs

const apiRoutes = {
  "/api/login": () => import("../../../functions/api/login.js"),
  "/api/update": () => import("../../../functions/api/update.js"),
  "/api/update-stream": () => import("../../../functions/api/update-stream.js"),
  "/api/cancel-run": () => import("../../../functions/api/cancel-run.js"),
  "/api/schedule": () => import("../../../functions/api/schedule.js"),
  "/api/r2-diagnostics": () => import("../../../functions/api/r2-diagnostics.js"),
};
const dataRoute = /^\\/data\\/.+/;

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // 1) API handlers
    if (url.pathname.startsWith("/api/")) {
      const match = Object.prototype.hasOwnProperty.call(apiRoutes, url.pathname)
        ? url.pathname
        : null;
      if (!match) return new Response("Not Found", { status: 404 });

      const mod = await apiRoutes[match]();
      // Support both styles:
      // - default export: (req, {env,ctx}) => Response
      // - onRequest(context): Response
      if (typeof mod.default === "function") {
        return mod.default(request, { env, ctx });
      }
      if (typeof mod.onRequest === "function") {
        return mod.onRequest({ request, env, ctx });
      }
      return new Response("Bad handler", { status: 500 });
    }

    // 2) /data/* from R2
    if (dataRoute.test(url.pathname)) {
      if (!env?.LEADERBOARDS) return new Response("R2 not bound", { status: 500 });
      const key = decodeURIComponent(url.pathname.replace(/^\\/data\\/?/, ""));
      if (!key) return new Response("Not found", { status: 404 });

      const obj = await env.LEADERBOARDS.get(key);
      if (!obj) return new Response("Not found", { status: 404 });

      const isJSON = key.endsWith(".json");
      return new Response(obj.body, {
        headers: {
          "Content-Type": isJSON ? "application/json" : "application/octet-stream",
          "Cache-Control": isJSON
            ? "public, max-age=3600, stale-while-revalidate=59"
            : "public, max-age=604800, immutable",
          "Access-Control-Allow-Origin": "*",
        },
      });
    }

    // 3) Everything else -> Next’s generated worker
    const nextWorker = await import("./index.next.js");
    return nextWorker.default.fetch(request, env, ctx);
  }
};
`;

// write wrapper index.js
fs.writeFileSync(generatedIndex, wrapper, "utf8");

// 3) Remove routes file so the worker handles requests
try { fs.unlinkSync(routesJson); } catch {}

console.log("✔ Wrapped Next worker, mounted API + /data, and removed _routes.json");
